medgate_challenge:
  outputs:
    dev:
      dbname: airflow_db
      host: postgres
      pass: airflow
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: airflow
  target: dev